Repository monta-app/static, pull requests merged in 2024-04, with the labels that each got.

#30 Creating Plug4Us WL app Terms & Conditions and Privacy Policy files
  pt-plug4us-privacy-policy.md
  pt-plug4us-terms-and-conditions.md
Labels: missing-jira, S review

#32 feat(mobile-dependencies): Adding dependencies from the mobile app
  mobile-dependencies.md
  open-source.md
Labels: missing-jira, XL review

#35 Moving URL to monta domain
  open-source.md
Labels: missing-jira, XS review
