Repository monta-app/static, pull requests merged in 2024-10, with the labels that each got.

#46 Adding Uno-X privacy policy
  da-uno-x-privacy-policy.md
Labels: missing-jira, XS review

#45 Adding Uno-X terms of use
  da-uno-x-terms-of-use.md
Labels: missing-jira, S review

#47 Update da-uno-x-privacy-policy.md
  da-uno-x-privacy-policy.md
Labels: missing-jira, XS review

#48 Update da-uno-x-terms-of-use.md
  da-uno-x-terms-of-use.md
Labels: missing-jira, XS review

#41 Update siemens-terms-and-conditions-2.md
  siemens-terms-and-conditions-2.md
Labels: XS review

#40 feat: Added new Siemens terms and conditions
  siemens-terms-and-conditions-2.md
Labels: missing-jira, S review
